version: 2
updates:
  # ──────────────────────────────
  # Rust Backend
  # ──────────────────────────────
  - package-ecosystem: "cargo"
    directory: "/backend"           # Pfad zum Rust-Projekt (anpassen falls anders)
    schedule:
      interval: "daily"
      time: "07:30"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "cargo"
      include: "scope"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    reviewers:
      - "MickLesk"
    groups:
      cargo-deps:
        patterns:
          - "*"

  # ──────────────────────────────
  # Frontend (Svelte)
  # ──────────────────────────────
  - package-ecosystem: "npm"
    directory: "/frontend"          # Pfad zum SvelteKit-Projekt (anpassen falls anders)
    schedule:
      interval: "daily"
      time: "07:30"
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "npm"
      include: "scope"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    reviewers:
      - "MickLesk"
    groups:
      sveltekit-deps:
        patterns:
          - "svelte*"
          - "@sveltejs/*"
          - "vite*"
          - "@vitejs/*"
      frontend-libs:
        patterns:
          - "*"
        exclude-patterns:
          - "svelte*"
          - "@sveltejs/*"
          - "vite*"
          - "@vitejs/*"
